
USE meine_datenbank;


-- Create tables
CREATE TABLE CUSTOMER (
    CUSTOMER_ID VARCHAR(50) UNIQUE,
    NAME VARCHAR(100),
    STREET_NAME VARCHAR(100),
    HOUSE_NUMBER VARCHAR(10),
    POSTAL_CODE VARCHAR(10),
    CITY VARCHAR(100),
    COUNTRY VARCHAR(100)
);

CREATE TABLE BRANCH (
    NAME VARCHAR(100) PRIMARY KEY,
    STREET_NAME VARCHAR(100),
    HOUSE_NUMBER VARCHAR(10),
    POSTAL_CODE VARCHAR(10),
    CITY VARCHAR(100),
    COUNTRY VARCHAR(100)
);

CREATE TABLE EMPLOYEE (
    EMPLOYEE_ID VARCHAR(50) UNIQUE,
    NAME VARCHAR(100),
    BRANCH_NAME VARCHAR(100) REFERENCES BRANCH(NAME),
    SALARY DECIMAL(10,2),
    STREET_NAME VARCHAR(100),
    HOUSE_NUMBER VARCHAR(10),
    POSTAL_CODE VARCHAR(10),
    CITY VARCHAR(100),
    COUNTRY VARCHAR(100)
);

CREATE TABLE PRODUCT (
    PRODUCT_ID INTEGER PRIMARY KEY,
    NAME VARCHAR(100),
    DESCRIPTION TEXT,
    INGREDIENTS TEXT,
    PRICE DECIMAL(10,2)
);

CREATE TABLE STORAGE (
    STORAGE_ID INTEGER PRIMARY KEY,
    NAME VARCHAR(100),
    BRANCH VARCHAR(100) REFERENCES BRANCH(NAME),
    COST DECIMAL(10,2),
    QUANTITY INTEGER
);

CREATE TABLE ORDER (
    ORDER_ID INTEGER PRIMARY KEY,
    STATUS VARCHAR(50),
    CUSTOMER_ID VARCHAR(50) REFERENCES CUSTOMER(CUSTOMER_ID),
    PRODUCT_ID INTEGER REFERENCES PRODUCT(PRODUCT_ID),
    BRANCH_NAME VARCHAR(100) REFERENCES BRANCH(NAME),
    QUANTITY INTEGER,
    TOTAL_PRICE DECIMAL(10,2),
    ORDER_DATE TIMESTAMP
);

-- Insert sample data
INSERT INTO BRANCH (NAME, STREET_NAME, HOUSE_NUMBER, POSTAL_CODE, CITY, COUNTRY)
VALUES 
('Main Branch', 'Main Street', '123', '12345', 'Berlin', 'Germany'),
('East Branch', 'East Avenue', '456', '23456', 'Hamburg', 'Germany');

INSERT INTO CUSTOMER (CUSTOMER_ID, NAME, STREET_NAME, HOUSE_NUMBER, POSTAL_CODE, CITY, COUNTRY)
VALUES 
('CUST001', 'John Doe', 'Customer Street', '1', '12345', 'Berlin', 'Germany'),
('CUST002', 'Jane Smith', 'Customer Avenue', '2', '23456', 'Hamburg', 'Germany');

INSERT INTO PRODUCT (PRODUCT_ID, NAME, DESCRIPTION, INGREDIENTS, PRICE)
VALUES 
(1, 'Pizza Margherita', 'Classic Italian Pizza', 'Tomato, Mozzarella, Basil', 9.99),
(2, 'Pasta Carbonara', 'Traditional Roman Pasta', 'Pasta, Eggs, Pecorino, Guanciale', 12.99);